### ISSUE TITLE
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'

### ISSUE THREAD

**Issue by mehmetcanay** [SCAI-BIO/datastew#12]
I tried to install the package into [PDataViewer](https://github.com/SCAI-BIO/PDataViewer). The virtual environment uses python version 3.12.1  and pip version 24.1.2. I tried `pip install --upgrade virtualenv` and then `virtualenv venv --python=python3.12` with and without `--reset-app-data`. However, this does not solve the issue.  There is no error while installing with python3.11 so it is likely a problem with the python or pip version. I would be glad if you could inform me whether there is a way to mitigate this error without rolling back to python3.11. 

      error: subprocess-exited-with-error
      
      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> [33 lines of output]
          Traceback (most recent call last):
            File "/home/may/git/PDataViewer/backend/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/home/may/git/PDataViewer/backend/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/home/may/git/PDataViewer/backend/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
              backend = _build_backend()
                        ^^^^^^^^^^^^^^^^
            File "/home/may/git/PDataViewer/backend/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
              obj = import_module(mod_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^
            File "/home/may/.pyenv/versions/3.12.1/lib/python3.12/importlib/__init__.py", line 90, in import_module
              return _bootstrap._gcd_import(name[level:], package, level)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
            File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
            File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
            File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
            File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
            File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
            File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
            File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
            File "<frozen importlib._bootstrap_external>", line 994, in exec_module
            File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
            File "/tmp/pip-build-env-8q0wgqek/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
              import setuptools.version
            File "/tmp/pip-build-env-8q0wgqek/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
              import pkg_resources
            File "/tmp/pip-build-env-8q0wgqek/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
              register_finder(pkgutil.ImpImporter, find_on_path)
                              ^^^^^^^^^^^^^^^^^^^
          AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by tiadams** [comment]
@mehmetcanay Is this still an issue?

**Comment by mehmetcanay** [comment]
@tiadams PDataViewer no longer utilizes the datastew module but only its API (index). Since the tests for python version 3.12 are passing, I doubt that this error will re-occur if someone tries to install the module directly into their project. Use of python3.12 was causing the problem back then for PDataViewer which I tried to solve by falling back to python3.11.

**Comment by mehmetcanay** [comment]
I think we solved this by migrating to Poetry @tiadams
